// Code generated by ogen, DO NOT EDIT.

package openapi

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/ConflictError
type ConflictError struct {
	Error   OptString `json:"error"`
	Message OptString `json:"message"`
}

// GetError returns the value of Error.
func (s *ConflictError) GetError() OptString {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *ConflictError) GetMessage() OptString {
	return s.Message
}

// SetError sets the value of Error.
func (s *ConflictError) SetError(val OptString) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *ConflictError) SetMessage(val OptString) {
	s.Message = val
}

func (*ConflictError) registerRes() {}

type Email string

// Ref: #/components/schemas/ForbiddenError
type ForbiddenError struct {
	Error   OptString `json:"error"`
	Message OptString `json:"message"`
}

// GetError returns the value of Error.
func (s *ForbiddenError) GetError() OptString {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *ForbiddenError) GetMessage() OptString {
	return s.Message
}

// SetError sets the value of Error.
func (s *ForbiddenError) SetError(val OptString) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *ForbiddenError) SetMessage(val OptString) {
	s.Message = val
}

func (*ForbiddenError) getUserRes() {}
func (*ForbiddenError) loginRes()   {}

// Ref: #/components/schemas/InternalServerError
type InternalServerError struct {
	Error   OptString `json:"error"`
	Message OptString `json:"message"`
}

// GetError returns the value of Error.
func (s *InternalServerError) GetError() OptString {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() OptString {
	return s.Message
}

// SetError sets the value of Error.
func (s *InternalServerError) SetError(val OptString) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val OptString) {
	s.Message = val
}

func (*InternalServerError) getUserRes()  {}
func (*InternalServerError) loginRes()    {}
func (*InternalServerError) registerRes() {}

type LoginReq struct {
	Name         OptName         `json:"name"`
	Email        OptEmail        `json:"email"`
	PasswordHash OptPasswordHash `json:"password_hash"`
}

// GetName returns the value of Name.
func (s *LoginReq) GetName() OptName {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *LoginReq) GetEmail() OptEmail {
	return s.Email
}

// GetPasswordHash returns the value of PasswordHash.
func (s *LoginReq) GetPasswordHash() OptPasswordHash {
	return s.PasswordHash
}

// SetName sets the value of Name.
func (s *LoginReq) SetName(val OptName) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *LoginReq) SetEmail(val OptEmail) {
	s.Email = val
}

// SetPasswordHash sets the value of PasswordHash.
func (s *LoginReq) SetPasswordHash(val OptPasswordHash) {
	s.PasswordHash = val
}

type LoginResponse struct {
	// APIリクエストの際に使用するJWTアクセストークン。有効期限は短い。.
	AccessToken OptString `json:"accessToken"`
	// アクセストークンの有効期限が切れた際に、新しいトークンを再発行するために使用するトークン。有効期限は長い。.
	RefreshToken OptString `json:"refreshToken"`
}

// GetAccessToken returns the value of AccessToken.
func (s *LoginResponse) GetAccessToken() OptString {
	return s.AccessToken
}

// GetRefreshToken returns the value of RefreshToken.
func (s *LoginResponse) GetRefreshToken() OptString {
	return s.RefreshToken
}

// SetAccessToken sets the value of AccessToken.
func (s *LoginResponse) SetAccessToken(val OptString) {
	s.AccessToken = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *LoginResponse) SetRefreshToken(val OptString) {
	s.RefreshToken = val
}

func (*LoginResponse) loginRes() {}

type Name string

// NewOptEmail returns new OptEmail with value set to v.
func NewOptEmail(v Email) OptEmail {
	return OptEmail{
		Value: v,
		Set:   true,
	}
}

// OptEmail is optional Email.
type OptEmail struct {
	Value Email
	Set   bool
}

// IsSet returns true if OptEmail was set.
func (o OptEmail) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptEmail) Reset() {
	var v Email
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptEmail) SetTo(v Email) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptEmail) Get() (v Email, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptEmail) Or(d Email) Email {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptLoginReq returns new OptLoginReq with value set to v.
func NewOptLoginReq(v LoginReq) OptLoginReq {
	return OptLoginReq{
		Value: v,
		Set:   true,
	}
}

// OptLoginReq is optional LoginReq.
type OptLoginReq struct {
	Value LoginReq
	Set   bool
}

// IsSet returns true if OptLoginReq was set.
func (o OptLoginReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptLoginReq) Reset() {
	var v LoginReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptLoginReq) SetTo(v LoginReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptLoginReq) Get() (v LoginReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptLoginReq) Or(d LoginReq) LoginReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptName returns new OptName with value set to v.
func NewOptName(v Name) OptName {
	return OptName{
		Value: v,
		Set:   true,
	}
}

// OptName is optional Name.
type OptName struct {
	Value Name
	Set   bool
}

// IsSet returns true if OptName was set.
func (o OptName) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptName) Reset() {
	var v Name
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptName) SetTo(v Name) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptName) Get() (v Name, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptName) Or(d Name) Name {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPasswordHash returns new OptPasswordHash with value set to v.
func NewOptPasswordHash(v PasswordHash) OptPasswordHash {
	return OptPasswordHash{
		Value: v,
		Set:   true,
	}
}

// OptPasswordHash is optional PasswordHash.
type OptPasswordHash struct {
	Value PasswordHash
	Set   bool
}

// IsSet returns true if OptPasswordHash was set.
func (o OptPasswordHash) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPasswordHash) Reset() {
	var v PasswordHash
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPasswordHash) SetTo(v PasswordHash) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPasswordHash) Get() (v PasswordHash, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPasswordHash) Or(d PasswordHash) PasswordHash {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRegisterReq returns new OptRegisterReq with value set to v.
func NewOptRegisterReq(v RegisterReq) OptRegisterReq {
	return OptRegisterReq{
		Value: v,
		Set:   true,
	}
}

// OptRegisterReq is optional RegisterReq.
type OptRegisterReq struct {
	Value RegisterReq
	Set   bool
}

// IsSet returns true if OptRegisterReq was set.
func (o OptRegisterReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRegisterReq) Reset() {
	var v RegisterReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRegisterReq) SetTo(v RegisterReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRegisterReq) Get() (v RegisterReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRegisterReq) Or(d RegisterReq) RegisterReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type PasswordHash string

// RegisterCreated is response for Register operation.
type RegisterCreated struct{}

func (*RegisterCreated) registerRes() {}

type RegisterReq struct {
	Name         OptName         `json:"name"`
	Email        OptEmail        `json:"email"`
	PasswordHash OptPasswordHash `json:"password_hash"`
}

// GetName returns the value of Name.
func (s *RegisterReq) GetName() OptName {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *RegisterReq) GetEmail() OptEmail {
	return s.Email
}

// GetPasswordHash returns the value of PasswordHash.
func (s *RegisterReq) GetPasswordHash() OptPasswordHash {
	return s.PasswordHash
}

// SetName sets the value of Name.
func (s *RegisterReq) SetName(val OptName) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *RegisterReq) SetEmail(val OptEmail) {
	s.Email = val
}

// SetPasswordHash sets the value of PasswordHash.
func (s *RegisterReq) SetPasswordHash(val OptPasswordHash) {
	s.PasswordHash = val
}

// Ref: #/components/schemas/UnauthorizedError
type UnauthorizedError struct {
	Error   OptString `json:"error"`
	Message OptString `json:"message"`
}

// GetError returns the value of Error.
func (s *UnauthorizedError) GetError() OptString {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *UnauthorizedError) GetMessage() OptString {
	return s.Message
}

// SetError sets the value of Error.
func (s *UnauthorizedError) SetError(val OptString) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *UnauthorizedError) SetMessage(val OptString) {
	s.Message = val
}

func (*UnauthorizedError) getUserRes() {}
func (*UnauthorizedError) loginRes()   {}

type UserResponse struct {
	Name         OptName         `json:"name"`
	Email        OptEmail        `json:"email"`
	PasswordHash OptPasswordHash `json:"password_hash"`
}

// GetName returns the value of Name.
func (s *UserResponse) GetName() OptName {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *UserResponse) GetEmail() OptEmail {
	return s.Email
}

// GetPasswordHash returns the value of PasswordHash.
func (s *UserResponse) GetPasswordHash() OptPasswordHash {
	return s.PasswordHash
}

// SetName sets the value of Name.
func (s *UserResponse) SetName(val OptName) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *UserResponse) SetEmail(val OptEmail) {
	s.Email = val
}

// SetPasswordHash sets the value of PasswordHash.
func (s *UserResponse) SetPasswordHash(val OptPasswordHash) {
	s.PasswordHash = val
}

func (*UserResponse) getUserRes() {}

// Ref: #/components/schemas/ValidationError
type ValidationError struct {
	Error   OptString `json:"error"`
	Message OptString `json:"message"`
}

// GetError returns the value of Error.
func (s *ValidationError) GetError() OptString {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *ValidationError) GetMessage() OptString {
	return s.Message
}

// SetError sets the value of Error.
func (s *ValidationError) SetError(val OptString) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *ValidationError) SetMessage(val OptString) {
	s.Message = val
}

func (*ValidationError) loginRes()    {}
func (*ValidationError) registerRes() {}
